INSERT INTO `sports` (`id`, `parent_id`, `name`, `options`, `status`, `created`, `modified`) VALUES
(1, 0, 'Without Sport Group', NULL, 1, NOW(), NOW()),
(2, 0, 'Strength and Fitness', NULL, 1, NOW(), NOW()),
(3, 0, 'Individual Sports', NULL, 1, NOW(), NOW()),
(4, 0, 'Team Sports', NULL, 1, NOW(), NOW()),
(5, 0, 'Trend Sports', NULL, 1, NOW(), NOW()),
(6, 0, 'Martial Arts', NULL, 1, NOW(), NOW()),
(7, 0, 'Racquet Games', NULL, 1, NOW(), NOW()),
(11, 1, NULL, 'Nothing', 1, NOW(), NOW()),
(12, 1, NULL, 'Figure Skating', 1, NOW(), NOW()),
(13, 1, NULL, 'Artistic Cycling', 1, NOW(), NOW()),
(14, 1, NULL, 'Dance', 1, NOW(), NOW()),
(15, 1, NULL, 'Rowing', 1, NOW(), NOW()),
(16, 1, NULL, 'Sports Student', 1, NOW(), NOW()),
(17, 2, NULL, 'Fitness', 1, NOW(), NOW()),
(18, 2, NULL, 'Weight Training', 1, NOW(), NOW()),
(19, 2, NULL, 'Weight Training', 1, NOW(), NOW()),
(20, 2, NULL, 'Strength-Fitness', 1, NOW(), NOW()),
(21, 3, NULL, 'Vaulting', 1, NOW(), NOW()),
(22, 3, NULL, 'Weightlifting', 1, NOW(), NOW()),
(23, 3, NULL, 'Crossfit', 1, NOW(), NOW()),
(24, 3, NULL, 'Kickboxing', 1, NOW(), NOW()),
(25, 3, NULL, 'Apparatus Gymnastics', 1, NOW(), NOW()),
(26, 3, NULL, 'Modern Pentathlon', 1, NOW(), NOW()),
(27, 3, NULL, 'Canoe', 1, NOW(), NOW()),
(28, 3, NULL, 'Climb', 1, NOW(), NOW()),
(29, 3, NULL, 'Artistic Gymnastics', 1, NOW(), NOW()),
(30, 3, NULL, 'Jogging / Running', 1, NOW(), NOW()),
(31, 3, NULL, 'Athletics', 1, NOW(), NOW()),
(32, 3, NULL, 'Mountain Bike', 1, NOW(), NOW()),
(33, 3, NULL, 'Cycling', 1, NOW(), NOW()),
(34, 3, NULL, 'Swimming', 1, NOW(), NOW()),
(35, 3, NULL, 'Gymnastics', 1, NOW(), NOW()),
(36, 3, NULL, 'Triathlon', 1, NOW(), NOW()),
(37, 4, NULL, 'Basketball', 1, NOW(), NOW()),
(38, 4, NULL, 'Football', 1, NOW(), NOW()),
(39, 4, NULL, 'Handball', 1, NOW(), NOW()),
(40, 4, NULL, 'Water Polo', 1, NOW(), NOW()),
(41, 4, NULL, 'Ice Hockey', 1, NOW(), NOW()),
(42, 5, NULL, 'Curling', 1, NOW(), NOW()),
(43, 5, NULL, 'Paragliding', 1, NOW(), NOW()),
(44, 5, NULL, 'Kite Surfing', 1, NOW(), NOW()),
(45, 5, NULL, 'Windsurfing', 1, NOW(), NOW()),
(46, 5, NULL, 'Diving', 1, NOW(), NOW()),
(47, 5, NULL, 'Parkour', 1, NOW(), NOW()),
(48, 5, NULL, 'Snowboarding', 1, NOW(), NOW()),
(49, 6, NULL, 'Judo', 1, NOW(), NOW()),
(50, 6, NULL, 'Thai Boxing', 1, NOW(), NOW()),
(51, 6, NULL, 'Taekwondo', 1, NOW(), NOW()),
(52, 6, NULL, 'Ju-Jutsu', 1, NOW(), NOW()),
(53, 6, NULL, 'Jiu jitsu', 1, NOW(), NOW()),
(54, 7, NULL, 'Volleyball', 1, NOW(), NOW()),
(55, 7, NULL, 'Tennis', 1, NOW(), NOW()),
(56, 7, NULL, 'Table Tennis', 1, NOW(), NOW()),
(57, 7, NULL, 'Beachvolleyball', 1, NOW(), NOW()),
(58, 7, NULL, 'Badminton', 1, NOW(), NOW()),
(59, 3, NULL, 'Golf', 1, NOW(), NOW());