LOCALHOST='127.0.0.1';
ALL='%';

mysql -u root -p"$MYSQL_ROOT_PASSWORD" --execute \
"CREATE USER IF NOT EXISTS 'root'@'${ALL}' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'${ALL}' IDENTIFIED BY '${MYSQL_PASSWORD}';
CREATE USER IF NOT EXISTS 'dbviewer'@'${ALL}' IDENTIFIED BY '${MYSQL_PASSWORD}';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON regmondb.* TO '${MYSQL_USER}'@'${ALL}';
GRANT SELECT ON regmondb.* TO 'dbviewer'@'${ALL}';
FLUSH PRIVILEGES;
"
