NETWORK='%.%.%.%';

mysql -u root -p$MYSQL_ROOT_PASSWORD --execute \
"CREATE USER IF NOT EXISTS 'root'@'${NETWORK}' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'${NETWORK}' IDENTIFIED BY '${MYSQL_PASSWORD}';
CREATE USER IF NOT EXISTS 'dbviewer'@'${NETWORK}' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'${NETWORK}';
GRANT SELECT, INSERT, UPDATE, DELETE ON regmondb.* TO 'dbuser'@'${NETWORK}';
GRANT SELECT ON regmondb.* TO 'dbviewer'@'${NETWORK}';
DROP USER IF EXISTS 'root'@'%';
DROP USER IF EXISTS 'dbuser'@'%';"
