--
-- Daten für Tabelle `sports`
--

INSERT INTO `sports` (`id`, `parent_id`, `name`, `options`, `status`, `created`, `modified`) VALUES
(1, 0, 'Ohne Zuordnung', NULL, 1, NOW(), NOW()),
(2, 0, 'Kraft und Fitness', NULL, 1, NOW(), NOW()),
(3, 0, 'Individualsportarten', NULL, 1, NOW(), NOW()),
(4, 0, 'Mannschaftssportarten', NULL, 1, NOW(), NOW()),
(5, 0, 'Trendsportarten', NULL, 1, NOW(), NOW()),
(6, 0, 'Kampfsport', NULL, 1, NOW(), NOW()),
(7, 0, 'Rückschlagspiele', NULL, 1, NOW(), NOW()),
(11, 1, NULL, 'Keine', 1, NOW(), NOW()),
(12, 1, NULL, 'Eiskunstlauf', 1, NOW(), NOW()),
(13, 1, NULL, 'Kunstradfahren', 1, NOW(), NOW()),
(14, 1, NULL, 'Tanzen', 1, NOW(), NOW()),
(15, 1, NULL, 'Rudern', 1, NOW(), NOW()),
(16, 1, NULL, 'Sportstudent', 1, NOW(), NOW()),
(17, 2, NULL, 'Fitness', 1, NOW(), NOW()),
(18, 2, NULL, 'Kraftsport', 1, NOW(), NOW()),
(19, 2, NULL, 'Krafttraining', 1, NOW(), NOW()),
(20, 2, NULL, 'Kraft-Fitness', 1, NOW(), NOW()),
(21, 3, NULL, 'Voltigieren', 1, NOW(), NOW()),
(22, 3, NULL, 'Gewichtheben', 1, NOW(), NOW()),
(23, 3, NULL, 'Crossfit', 1, NOW(), NOW()),
(24, 3, NULL, 'Kickboxen', 1, NOW(), NOW()),
(25, 3, NULL, 'Geräteturnen', 1, NOW(), NOW()),
(26, 3, NULL, 'Moderner Fünfkampf', 1, NOW(), NOW()),
(27, 3, NULL, 'Kanu', 1, NOW(), NOW()),
(28, 3, NULL, 'Klettern', 1, NOW(), NOW()),
(29, 3, NULL, 'Kunstturnen', 1, NOW(), NOW()),
(30, 3, NULL, 'Jogging / Laufen', 1, NOW(), NOW()),
(31, 3, NULL, 'Leichtathletik', 1, NOW(), NOW()),
(32, 3, NULL, 'Mountainbike', 1, NOW(), NOW()),
(33, 3, NULL, 'Radsport', 1, NOW(), NOW()),
(34, 3, NULL, 'Schwimmen', 1, NOW(), NOW()),
(35, 3, NULL, 'Turnen', 1, NOW(), NOW()),
(36, 3, NULL, 'Triathlon', 1, NOW(), NOW()),
(37, 4, NULL, 'Basketball', 1, NOW(), NOW()),
(38, 4, NULL, 'Fußball', 1, NOW(), NOW()),
(39, 4, NULL, 'Handball', 1, NOW(), NOW()),
(40, 4, NULL, 'Wasserball', 1, NOW(), NOW()),
(41, 4, NULL, 'Eishockey', 1, NOW(), NOW()),
(42, 5, NULL, 'Curling', 1, NOW(), NOW()),
(43, 5, NULL, 'Paragliding', 1, NOW(), NOW()),
(44, 5, NULL, 'Kitesurfen', 1, NOW(), NOW()),
(45, 5, NULL, 'Windsurfen', 1, NOW(), NOW()),
(46, 5, NULL, 'Tauchen', 1, NOW(), NOW()),
(47, 5, NULL, 'Parkour', 1, NOW(), NOW()),
(48, 5, NULL, 'Snowboarding', 1, NOW(), NOW()),
(49, 6, NULL, 'Judo', 1, NOW(), NOW()),
(50, 6, NULL, 'Thaiboxen', 1, NOW(), NOW()),
(51, 6, NULL, 'Taekwondo', 1, NOW(), NOW()),
(52, 6, NULL, 'Ju-Jutsu', 1, NOW(), NOW()),
(53, 6, NULL, 'Jiu jitsu', 1, NOW(), NOW()),
(54, 7, NULL, 'Volleyball', 1, NOW(), NOW()),
(55, 7, NULL, 'Tennis', 1, NOW(), NOW()),
(56, 7, NULL, 'Tischtennis', 1, NOW(), NOW()),
(57, 7, NULL, 'Beachvolleyball', 1, NOW(), NOW()),
(58, 7, NULL, 'Badminton', 1, NOW(), NOW()),
(59, 3, NULL, 'Golf', 1, NOW(), NOW());